[package]
name = "totp"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { path = "../application" }
totp-rs = "5.7.0"
rand = "0.9.2"
base32 = "0.5.1"
log = "0.4.29"
async-trait = "0.1.89"
