[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
web-sys = "0.3.83"
yew = { version = "0.22.0", features = ["csr"] }
wasm-bindgen-futures = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
yew-router = "0.19.0"
